// This file is generated by `flutterfire configure`.
// You must configure Firebase using the FlutterFire CLI before building.
// Run: `flutterfire configure` in your project root.
//
// For now this stub allows the project to compile.
// Replace this file with the output of `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Please run `flutterfire configure` to generate options.',
        );
    }
  }

  // ─── REPLACE THESE WITH YOUR REAL FIREBASE VALUES ─────────────────────────
  // Run: `flutterfire configure` after adding your app to Firebase Console.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJh6KVPVOsAwIblQ_mBmD5DA46yLzluo',
    appId: '1:610164037393:web:0c5cde79c95aad26889eb0',
    messagingSenderId: '610164037393',
    projectId: 'planea-a0179',
    authDomain: 'planea-a0179.firebaseapp.com',
    storageBucket: 'planea-a0179.firebasestorage.app',
    measurementId: 'G-D5Q2MDTZ73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzg7pL3aQI1KjmbwH-Zrk0wRVxWAZbo4',
    appId: '1:610164037393:android:a01cdb483320cb6b889eb0',
    messagingSenderId: '610164037393',
    projectId: 'planea-a0179',
    storageBucket: 'planea-a0179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdD2xe52cuuh0DNik1CB2Vi6JmIw7vb-E',
    appId: '1:610164037393:ios:980a8371e2ca07a0889eb0',
    messagingSenderId: '610164037393',
    projectId: 'planea-a0179',
    storageBucket: 'planea-a0179.firebasestorage.app',
    iosBundleId: 'com.planea.planea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-planea-project',
    storageBucket: 'your-planea-project.appspot.com',
    iosBundleId: 'com.planea.planea',
  );
}